resources:

  - name: node-img
    type: image
    integration: dr-dockerhub
    pointer:
      sourceName: "devopsrecipes/release-push-docker-hub"
    seed:
      versionName: master.2
    flags:
      - release-from-upstream-release-jobs

  - name: node-img-opts
    type: dockerOptions
    version:
      memory: 128
      cpuShares: 256
      portMappings:
        - 8180:8180
      publishAllPorts : true
    flags:
      - release-from-upstream-release-jobs

  - name: java-img
    type: image
    integration: dr-ecr
    pointer:
      sourceName: "679404489841.dkr.ecr.us-west-2.amazonaws.com/devopsrecipes-java-ecr"
    seed:
      versionName: master.12
    flags:
      - release-from-upstream-release-jobs

  - name: java-img-opts
    type: dockerOptions
    version:
      memory: 128
      cpuShares: 256
      portMappings:
        - 8280:8280
      publishAllPorts : true
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-ecs-cluster
    type: cluster
    integration: dr-aws
    pointer:
      sourceName : "release-multiple-component-cs"
      region: "us-west-2"
    flags:
      - release-from-upstream-release-jobs

  - name: upstream-release-version
    type: version
    seed:
      versionName: "1.0.0"
    flags:
      - release-from-upstream-release-jobs

jobs:

  - name: release-from-upstream-release-node-img-manifest-job
    type: manifest
    steps:
      - IN: node-img
      - IN: node-img-opts
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-java-img-manifest-job
    type: manifest
    steps:
      - IN: java-img
      - IN: java-img-opts
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-upstream-release-job
    type: release
    bump: beta
    steps:
      - IN: release-from-upstream-release-node-img-manifest-job
      - IN: release-from-upstream-release-java-img-manifest-job
      - IN: upstream-release-version
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-deploy-ecs-job
    type: deploy
    steps:
      - IN: release-from-upstream-release-upstream-release-job
      - IN: release-from-upstream-release-ecs-cluster
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-downstream-release-job
    type: release
    bump: rc
    steps:
      - IN: release-from-upstream-release-deploy-ecs-job
    flags:
      - release-from-upstream-release-jobs
