jobs:

  - name: release-from-upstream-release-node-img-manifest-job
    type: manifest
    steps:
      - IN: node-img
      - IN: node-img-opts
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-java-img-manifest-job
    type: manifest
    steps:
      - IN: java-img
      - IN: java-img-opts
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-upstream-release-job
    type: release
    steps:
      - IN: release-from-upstream-release-node-img-manifest-job
      - IN: release-from-upstream-release-java-img-manifest-job
      - IN: upstream-release-version
      - TASK: managed
        bump: beta
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-deploy-ecs-job
    type: deploy
    steps:
      - IN: release-from-upstream-release-upstream-release-job
      - IN: release-from-upstream-release-ecs-cluster
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-downstream-release-job
    type: release
    steps:
      - IN: release-from-upstream-release-deploy-ecs-job
      - TASK: managed
        bump: rc
    flags:
      - release-from-upstream-release-jobs

