jobs:

  - name: release-single-component_runCI
    type: runCI
    steps:
      - OUT: node-img
    flags:
      - release-from-upstream-release-jobs

  - name: ci-java-ecr_runCI
    type: runCI
    steps:
      - OUT: java-img
    flags:
      - release-from-upstream-release-jobs

  - name: node-img-manifest
    type: manifest
    steps:
      - IN: node-img
      - IN: node-img-opts
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: java-img-manifest
    type: manifest
    steps:
      - IN: java-img
      - IN: java-img-opts
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: upstream-release-job
    type: release
    steps:
      - IN: java-img-manifest
      - IN: node-img-manifest
      - IN: upstream-release-version
      - TASK: managed
        bump: beta
    flags:
      - release-from-upstream-release-jobs

  - name: release-from-upstream-release-deploy-ecs
    type: deploy
    steps:
      - IN: upstream-release-job
      - IN: release-from-upstream-release-ecs-cluster
      - TASK: managed
    flags:
      - release-from-upstream-release-jobs

  - name: downstream-release-job
    type: release
    steps:
      - IN: release-from-upstream-release-deploy-ecs
      - TASK: managed
        bump: rc
    flags:
      - release-from-upstream-release-jobs

